# CANDLESTICK PATTERNS IN TRADING: A Data-Driven Journey

This Jupyter notebook couples with the Medium article "Candlestick Patterns in Trading: A Data-Driven Journey". It demonstrates the process of acquiring stock data, preprocessing it, identifying candlestick patterns, and visualizing the results using Python and various libraries like yfinance and Plotly.

In [1]:
#import os
import random
import numpy as np
import pandas as pd
import yfinance as yf
import plotly.graph_objects as go
#from dotenv import load_dotenv

Reading this notebook via GitHub folder will NOT show the interactive Plotly charts. I STRONGLY suggest you to run this code in your local machine.

### DATA RETRIEVAL

In this section, we'll use the yfinance library to fetch historical stock data for Apple Inc. (AAPL) from 1995 onwards.

In [2]:
# Define the ticker symbol
ticker = 'AAPL'

# Define the start date
start_date = '1995-01-01'

# Initialize the stock
stock = yf.Ticker(ticker)

stock_data = {}
# Retrieve the data regarding the stock
stock_info = stock.info
historical_data = stock.history(start=start_date)
splits = stock.splits
stock_data[ticker] = {
            'info': stock_info,
            'historical_data': historical_data,
            'splits': splits,
        }

In [3]:
stock_data[ticker]['splits']

Date
1987-06-16 00:00:00-04:00    2.0
2000-06-21 00:00:00-04:00    2.0
2005-02-28 00:00:00-05:00    2.0
2014-06-09 00:00:00-04:00    7.0
2020-08-31 00:00:00-04:00    4.0
Name: Stock Splits, dtype: float64

In [4]:
# Define the dataset we will work on
df = stock_data[ticker]['historical_data']

In [5]:
df.head(10)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1995-01-03 00:00:00-05:00,0.288185,0.288185,0.280773,0.284479,103868800,0.0,0.0
1995-01-04 00:00:00-05:00,0.286332,0.293746,0.286332,0.291892,158681600,0.0,0.0
1995-01-05 00:00:00-05:00,0.290965,0.291893,0.287259,0.288185,73640000,0.0,0.0
1995-01-06 00:00:00-05:00,0.308572,0.319692,0.304865,0.311352,1076622400,0.0,0.0
1995-01-09 00:00:00-05:00,0.308572,0.310425,0.303938,0.305444,274086400,0.0,0.0
1995-01-10 00:00:00-05:00,0.305792,0.326178,0.305792,0.323861,614790400,0.0,0.0
1995-01-11 00:00:00-05:00,0.324325,0.356293,0.316448,0.346564,873824000,0.0,0.0
1995-01-12 00:00:00-05:00,0.341931,0.343785,0.331738,0.336371,551779200,0.0,0.0
1995-01-13 00:00:00-05:00,0.341930,0.341930,0.328957,0.332665,351377600,0.0,0.0
1995-01-16 00:00:00-05:00,0.332665,0.335444,0.328031,0.329884,188977600,0.0,0.0

In [6]:
df.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,7821.000000,7821.000000,7821.000000,7821.000000,7.821000e+03,7821.000000,7821.000000
mean,41.100005,41.542762,40.682702,41.130690,3.699297e+08,0.001250,0.001918
std,66.717920,67.427259,66.064074,66.775554,3.746229e+08,0.015601,0.096599
min,0.096533,0.099346,0.095596,0.097002,1.791060e+07,0.000000,0.000000
25%,0.368440,0.375638,0.361392,0.370690,1.139909e+08,0.000000,0.000000
50%,7.753586,7.809069,7.657013,7.757786,2.555952e+08,0.000000,0.000000
75%,40.660037,40.976666,40.435628,40.683899,4.835012e+08,0.000000,0.000000
max,286.200012,288.619995,283.299988,286.190002,7.421641e+09,0.260000,7.000000

### DATA CLEANING

Raw financial data often contains inconsistencies and errors. Here, we'll clean our dataset by removing invalid entries and rounding prices to appropriate decimal places.

In [7]:
initial_rows = len(df)
# Remove rows with missing values
df = df.dropna(subset=['Open', 'High', 'Low', 'Close'], how='any')

# Remove rows with negative prices (valid for stocks)
df = df[(df['Open'] > 0) & (df['High'] > 0) & (df['Low'] > 0) & (df['Close'] > 0)]

# Remove rows with Open, High, Low, Close values that don't make sense
df = df[df['High'] >= df['Low']]
df = df[df['High'] >= df['Open']]
df = df[df['High'] >= df['Close']]
df = df[df['Low'] <= df['Open']]
df = df[df['Low'] <= df['Close']]

final_rows = len(df)
if initial_rows != final_rows:
    print(f'{initial_rows - final_rows} rows were removed from {ticker} dataset because of missing or incorrect data')

4 rows were removed from AAPL dataset because of missing or incorrect data

Let's round the values of the prices.

In [8]:
columns_to_round = ['Open', 'High', 'Low', 'Close']
# Rules: price > 10: round to 2 decimal places; price > 1: round to 3 decimal places; price < 1: round to 4 decimal places
for column in columns_to_round:
        df[column] = df[column].apply(lambda x: round(x, 2) if x > 10 else round(x, 3) if x > 1 else round(x, 4))

Let's check for anomalies within the dataset: occurrences which may be correct but should be investigated, especially if they are recurrent in the dataset.

In [9]:
# Dates with OHLC all the same
same_price_dates = df[(df['Open'] == df['High']) & (df['High'] == df['Low']) & (df['Low'] == df['Close'])].index.tolist()

# Dates with low volume
low_volume_dates = df[df['Volume'] < 1000].index.tolist()

# Calculate the average price
avgPrice = df[['Open', 'High', 'Low', 'Close']].mean(axis=1)

# Calculate the excursion of the average price
max_avg_price = avgPrice.max()
min_avg_price = avgPrice.min()
pct_excursion = (max_avg_price - min_avg_price) / min_avg_price * 100

if same_price_dates:
    print(f"Ticker: {ticker} has the same OHLC prices on {len(same_price_dates)} dates")
    print(same_price_dates)

if low_volume_dates:
    print(f"Ticker: {ticker} has low volume on {len(low_volume_dates)} dates")
    print(low_volume_dates)

if pct_excursion < 75:
    print(f"Ticker: {ticker} has a price excursion of less than 75% in the whole period: {pct_excursion:.2f}%")

In [10]:
anomalies = {
    'Open-pClose Anomalies': [],
    'High-Low Anomalies': [],
    'Close-Open Anomalies': []
}
threshold1 = 0.35
threshold2 = 0.5
# Find other anomalies in the prices of the stock day by day
for i in range(1, len(df)):
    previous_close = df.iloc[i-1]['Close']
    current_open = df.iloc[i]['Open']
    current_high = df.iloc[i]['High']
    current_low = df.iloc[i]['Low']
    current_close = df.iloc[i]['Close']

    # Check if the open is more than 35% higher or lower than the previous close
    if abs(current_open - previous_close) / previous_close > threshold1:
        anomalies['Open-pClose Anomalies'].append((df.index[i], current_open, previous_close))

    # Check if the high-low excursion is more than 50%
    if (current_high - current_low) / current_low > threshold2:
        anomalies['High-Low Anomalies'].append((df.index[i], current_high, current_low))

    # Check if the close is more than 35% higher or lower than the open
    if abs(current_close - current_open) / current_open > threshold1:
        anomalies['Close-Open Anomalies'].append((df.index[i], current_close, current_open))

num_anomalies = sum([len(anomalies[key]) for key in anomalies.keys()])
if num_anomalies:
    print(f"Ticker: {ticker} has {num_anomalies} anomalies:")
    for key, value in anomalies.items():
        if value:
            print(f"  {key}: {len(value)}")
            print(value)

Ticker: AAPL has 1 anomalies:
  Open-pClose Anomalies: 1
[(Timestamp('2000-09-29 00:00:00-0400', tz='America/New_York'), 0.4227, 0.8023)]

If you find some anomalies it would be better to investigate their underlying reasons. If the dataset has too many recurrent anomalies or if the causes you found may be source of biased behavior in the stock prices, then the best option is to discard the stock!

### CANDLESTICK PLOT

Using Plotly, we'll create an interactive candlestick chart of the entire AAPL price history. This allows us to visually inspect the data and identify any obvious anomalies or trends.

In [11]:
fig = go.Figure( data = [go.Candlestick(x = df.index,
                    open  = df["Open"],
                    high  = df["High"],
                    low   = df["Low"],
                    close = df["Close"])],
                    )
# Add title, axis labels, remove rangeslider
fig.update_layout(title = dict(text = f'{ticker} Price from 1995 onwards',
                font = dict(size=18, color='red'),
                x = 0.5,
                ),
                yaxis_title = "Price (log)",
                xaxis_title = "Date",
                xaxis_rangeslider_visible = False,
                autosize = True,
                hovermode = 'x unified',
                )

fig.update_xaxes(showline = True, 
                linewidth = 2, 
                linecolor = 'black',
                mirror = True,
                tickangle = -45,
                )

fig.update_yaxes(type = "log",            # this adds a logarithmic scale on the y axis
                showgrid = True,
                gridcolor = 'blue', griddash = "dash",
                showline = True, linewidth = 2, 
                linecolor = 'black', mirror = True,
                )

fig.show()

### CANDLESTICK PATTERN

We'll focus on identifying the Bullish Engulfing pattern, a common reversal signal in technical analysis. We'll also calculate the Average True Range (ATR) to use as a filter for our pattern identification.

In [16]:
# Add the returns and log returns to the dataframe
df['Returns'] = df['Close'].pct_change()
df['Log_Returns'] = np.log(1 + df['Returns'])

# Start by calculating the ATR - Average True Range (will be used as filter)
period = 14     # standard ATR period
df['Prev_Close'] = df['Close'].shift(1)

# Calculate the True Range (TR)
df['TR'] = df[['High', 'Low', 'Prev_Close']].apply(
    lambda row: max(row['High'] - row['Low'], 
                    abs(row['High'] - row['Prev_Close']), 
                    abs(row['Low'] - row['Prev_Close'])), axis=1)

# Calculate the initial ATR as the rolling mean of the first 'period' TR values
df['ATR'] = df['TR'].rolling(window=period).mean()
# Calculate subsequent ATR values using the formula:
# ATR(i) = (ATR(i-1) * (period - 1) + TR(i)) / period
for i in range(period+1, len(df)):
    df.loc[df.index[i], 'ATR'] = (df.iloc[i-1]['ATR'] * (period - 1) + df.iloc[i]['TR']) / period

df.drop(columns=['Prev_Close'], inplace=True)

In [17]:
df.tail(10)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Returns,Log_Returns,TR,ATR
Date,,,,,,,,,,,
2026-01-15 00:00:00-05:00,260.65,261.04,257.05,258.21,39388600,0.0,0.0,-0.006732,-0.006755,3.99,4.367405
2026-01-16 00:00:00-05:00,257.90,258.90,254.93,255.53,72142800,0.0,0.0,-0.010379,-0.010433,3.97,4.339019
2026-01-20 00:00:00-05:00,252.73,254.79,243.42,246.70,80267500,0.0,0.0,-0.034556,-0.035167,12.11,4.894089
2026-01-21 00:00:00-05:00,248.70,251.56,245.18,247.65,54641700,0.0,0.0,0.003851,0.003843,6.38,5.000226
2026-01-22 00:00:00-05:00,249.20,251.00,248.15,248.35,39708300,0.0,0.0,0.002827,0.002823,3.35,4.882352
2026-01-23 00:00:00-05:00,247.32,249.41,244.68,248.04,41689000,0.0,0.0,-0.001248,-0.001249,4.73,4.871470
2026-01-26 00:00:00-05:00,251.48,256.56,249.80,255.41,55969200,0.0,0.0,0.029713,0.029280,8.52,5.132079
2026-01-27 00:00:00-05:00,259.17,261.95,258.21,258.27,49648300,0.0,0.0,0.011198,0.011135,6.54,5.232645
2026-01-28 00:00:00-05:00,257.65,258.86,254.51,256.44,41147100,0.0,0.0,-0.007086,-0.007111,4.35,5.169599
2026-01-29 00:00:00-05:00,258.07,259.65,254.41,257.04,24092385,0.0,0.0,0.002340,0.002337,5.24,5.174628

We will use the pattern known as Bullish Engulfing

In [18]:
# Calculate Bullish Engulfing pattern
body = abs(df['Close'] - df['Open'])
full_range = abs(df['High'] - df['Low'])
# Determine if the candle is bullish (True) or bearish (False)
direction = df['Close'] > df['Open']

# Shift columns to keep track of the previous candle
prev_open = df['Open'].shift(1)
prev_close = df['Close'].shift(1)
prev_body = body.shift(1)
prev_direction = direction.shift(1)

# Bullish engulfing pattern conditions
bullish_engulfing = (
    (direction == True) &           # current candle is bullish
    (prev_direction == False) &     # previous candle was bearish
    (df['Close'] > prev_open) &     # current close is higher than previous open
    (df['Open'] < prev_close)       # current open is lower than previous close
)

# Add any additional filters you choose
engulfing_mask = (
        bullish_engulfing &
        (body > 2 * prev_body) &
        (full_range >= 1*df['ATR'])
        # add more filters here if needed
    )

print(len(engulfing_mask))
print(f'The occurrences of Bullish Engulfing pattern in the dataset are {engulfing_mask.sum()}')

7817
The occurrences of Bullish Engulfing pattern in the dataset are 108

In [19]:
engulfing_mask

Date
1995-01-03 00:00:00-05:00    False
1995-01-04 00:00:00-05:00    False
1995-01-05 00:00:00-05:00    False
1995-01-06 00:00:00-05:00    False
1995-01-09 00:00:00-05:00    False
                             ...
2026-01-23 00:00:00-05:00    False
2026-01-26 00:00:00-05:00    False
2026-01-27 00:00:00-05:00    False
2026-01-28 00:00:00-05:00    False
2026-01-29 00:00:00-05:00    False
Length: 7817, dtype: bool

### VISUALISING IDENTIFIED PATTERNS

Finally, we'll create two visualizations:
1. A chart showing the entire price history with markers for each identified Bullish Engulfing pattern.
2. A multi-subplot chart showcasing individual instances of the pattern for closer inspection.

In [20]:
pattern_name = 'Bullish Engulfing'
fig = go.Figure()
    
# Add the close price line
fig.add_trace(go.Scatter(
    x = df.index,
    y = df['Close'],
    mode = 'lines',
    name = 'Close Price'
))

# Find the dates where patterns occur
pattern_dates = df.index[engulfing_mask]

# Add vertical lines and labels for each pattern
for date in pattern_dates:
    fig.add_shape(
        type = "line",
        x0 = date, x1 = date,
        y0 = 0, y1 = 1,
        yref = "paper",           # y-coordinate is in paper coordinates, that is normalized in [0, 1]
        line = dict(color="red", width=0.5, dash="dash"),
    )
    
    # Add a label with just the date (not time)
    fig.add_annotation(
        x = date - pd.Timedelta(hours=48),
        y = 0.05,
        yref = "paper",
        text = date.strftime('%Y-%m-%d'),
        showarrow = False,
        textangle = -90,
        font = dict(size=7, color='red'),
    )

fig.update_layout(
    title = dict(text = f'{ticker} Close Price with {pattern_name} occurrences',
                        font=dict(size=18, color='red'),
                        x=0.5,
                        ),
    xaxis_title = 'Date',
    yaxis_title = 'Close Price (log)',
    hovermode = 'x',
    autosize = True,
)

fig.update_xaxes(#showline = True, 
                linewidth = 1, 
                linecolor = 'black', mirror = True,
                tickangle = -45,
                )

fig.update_yaxes(type='log',
                linewidth = 1, 
                linecolor = 'black', mirror = True,
                )

fig.show()

In [22]:
from plotly.subplots import make_subplots

# Find the dates where patterns occur
pattern_dates = df.index[engulfing_mask]

# Select random dates from the pattern_dates up to k instances (which is the max number of subplots you want to show)
max_subplots = 12
section_dates = random.sample(list(pattern_dates), k=max_subplots)
section_dates = sorted(section_dates)

# Determine the number of rows and columns for the subplots
n_plots = len(section_dates)
n_cols = min(3, n_plots)        # max 3 columns
n_rows = (n_plots + n_cols - 1) // n_cols

# Define the number of candles to show in each subplot
max_candles = 20
back_candles = 5        # Number of candles before the engulfing pattern (which will be drawn)
num_candles = 2         # Number of candles in the engulfing pattern

# Create subplot figure
subplot_titles = [date.strftime('%B %d, %Y') for date in section_dates]
fig = make_subplots(rows=n_rows, cols=n_cols, 
                    vertical_spacing=0.1, horizontal_spacing=0.05,
                    subplot_titles=subplot_titles
                    )

for i, date in enumerate(section_dates):
    row = i // n_cols + 1
    col = i % n_cols + 1
    
    # Get the index of the engulfing pattern
    idx = df.index.get_loc(date)
    
    # Select data for the subplot. Must consider the back_candles and the num_candles
    start_idx = max(0, idx - back_candles)
    end_idx = min(len(df), start_idx + max_candles)
    subset = df.iloc[start_idx:end_idx]
    
    # create candlestick trace
    candlestick = go.Candlestick(
        x=subset.index,
        open=subset['Open'],
        high=subset['High'],
        low=subset['Low'],
        close=subset['Close'],
        showlegend=False,
        name = "",          # this is to avoid any trace number in the legend
    )
    
    fig.add_trace(candlestick, row=row, col=col)

    # add rectangle for candlestick pattern
    rect_start = subset.index[back_candles - num_candles + 1]    # First pattern candle
    rect_end = subset.index[back_candles]                           # Pattern candle

    # calculate extended x-coordinates for the rectangle
    x_left = rect_start - pd.Timedelta(hours=12)
    x_right = rect_end + pd.Timedelta(hours=12)
    
    rect_low = min(subset['Low'].iloc[back_candles-num_candles+1:back_candles+1]) * 0.998    # Extend 0.2% below
    rect_high = max(subset['High'].iloc[back_candles-num_candles+1:back_candles+1]) * 1.002  # Extend 0.2% above
    
    # create the rectangle trace
    rect = go.Scatter(
        x=[x_left, x_left, x_right, x_right, x_left],
        y=[rect_low, rect_high, rect_high, rect_low, rect_low],
        mode='lines',
        line=dict(color='red', width=1),
        fill='none',
        showlegend=False,
        hoverinfo='skip'    # No hover info for the rectangle
    )
    
    fig.add_trace(rect, row=row, col=col)
    
    # Update axes in each subplot
    fig.update_xaxes(title_text=None, showgrid=True, 
                    row=row, col=col, rangeslider_visible=False)
    if col == 1:
        fig.update_yaxes(title_text='Prices', showgrid=True, row=row, col=col)
    else:
        fig.update_yaxes(title_text=None, showgrid=True, row=row, col=col)
    #fig.update_yaxes(title_text=None, showgrid=True, row=row, col=col)

# Customize the layout of titles of the subplots
for annotation in fig['layout']['annotations']:
    annotation['font'] = dict(size=16)

fig.update_layout(
    #autosize = True,
    height=300*n_rows,  # Adjust height based on number of rows
    width=1100,         # Fixed width
    showlegend=False,
    hovermode='x unified', 
    title = dict(text = f'Examples of {pattern_name} detected in {ticker} stock',
                                font=dict(size=18, color='red'),
                                x=0.5)
    )

fig.show()

### CONCLUSION

This notebook demonstrates the process of identifying and visualizing candlestick patterns in stock data. The next steps would involve statistical analysis of these patterns to assess their predictive power and potential use in trading strategies.